
package br.com.epica.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EpicaWebServiceService", targetNamespace = "http://WS.epica.com.br/", wsdlLocation = "http://localhost:8080/EpicaWebService/EpicaWebService?wsdl")
public class EpicaWebServiceService
    extends Service
{

    private final static URL EPICAWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EPICAWEBSERVICESERVICE_EXCEPTION;
    private final static QName EPICAWEBSERVICESERVICE_QNAME = new QName("http://WS.epica.com.br/", "EpicaWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/EpicaWebService/EpicaWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EPICAWEBSERVICESERVICE_WSDL_LOCATION = url;
        EPICAWEBSERVICESERVICE_EXCEPTION = e;
    }

    public EpicaWebServiceService() {
        super(__getWsdlLocation(), EPICAWEBSERVICESERVICE_QNAME);
    }

    public EpicaWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EPICAWEBSERVICESERVICE_QNAME, features);
    }

    public EpicaWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, EPICAWEBSERVICESERVICE_QNAME);
    }

    public EpicaWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EPICAWEBSERVICESERVICE_QNAME, features);
    }

    public EpicaWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EpicaWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EpicaWebServiceInterface
     */
    @WebEndpoint(name = "EpicaWebServicePort")
    public EpicaWebServiceInterface getEpicaWebServicePort() {
        return super.getPort(new QName("http://WS.epica.com.br/", "EpicaWebServicePort"), EpicaWebServiceInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EpicaWebServiceInterface
     */
    @WebEndpoint(name = "EpicaWebServicePort")
    public EpicaWebServiceInterface getEpicaWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://WS.epica.com.br/", "EpicaWebServicePort"), EpicaWebServiceInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EPICAWEBSERVICESERVICE_EXCEPTION!= null) {
            throw EPICAWEBSERVICESERVICE_EXCEPTION;
        }
        return EPICAWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
